sudo: required
dist: trusty
language: generic

addons:
  apt:
    sources:
    - hvr-ghc
    - sourceline: 'ppa:hvr/ghcjs'
    - ubuntu-toolchain-r-test
    - sourceline: 'deb https://deb.nodesource.com/node_6.x trusty main'
      key_url: 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key'
    packages:
    - cabal-install-head
    - ghcjs-8.4
    - alex-3.1.4
    - happy-1.19.5

cache:
  bundler: false
  directories:
  - $HOME/.ghc/
  - $HOME/.ghcjs/
  - $HOME/.cabal/bin
  - $HOME/.cabal/share
  - $HOME/.cabal/lib
  - $HOME/.cabal/libexec
  - $HOME/.cabal/store

before_install:
    - export PATH=$HOME/.cabal/bin:$PATH
    - export PATH=/opt/ghc/bin:$PATH
    - export PATH=/opt/alex/3.1.4/bin:$PATH
    - export PATH=/opt/happy/1.19.5/bin:$PATH
    - export PATH=/opt/ghcjs/8.4/bin:$PATH
    - export PATH=$TRAVIS_BUILD_DIR/node_modules/.bin:$PATH
    - rm -f ~/.cabal/config
    - cabal update

install:
    # do not fail here, so that partial builds still warm the cache
    - cabal new-build --ghcjs --dependencies-only kaleidogen || true

jobs:
  include:
   - stage: warm cache with program dependencies
     if: type = api
     script:
       # dont actually build, we just want to warm the cache
       - ghcjs-pkg list

   - stage: build, test and deploy
     script:
       # now build
       - cabal new-build --ghcjs kaleidogen
       - cabal new-build --ghcjs kaleidogen-demo

     before_deploy:
       - cp -rv dist-newstyle/build/*/*/*/x/kaleidogen/build/*/*.jsexe gh-page
       - cp -rv dist-newstyle/build/*/*/*/x/kaleidogen-demo/build/*/*.jsexe gh-page/demo

     deploy:
       provider: pages
       local-dir: gh-page
       fqdn: kaleidogen.nomeata.de
       keep-history: false
       allow-empty-commit: true
       skip-cleanup: true
       github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
       on:
         branch: master

before_cache:
  - rm -rf $HOME/.ghcjs/*/ghcjs/ghcjs-boot/
  - du -sh $HOME/.ghcjs $HOME/.ghc $HOME/.cabal/bin $HOME/.cabal/lib $HOME/.cabal/config $HOME/.cabal/share

